// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @punch-remote/config
const encoding0 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.blobsKey)
    c.buffer.preencode(state, m.blobsDiscoveryKey)
  },
  encode (state, m) {
    c.buffer.encode(state, m.blobsKey)
    c.buffer.encode(state, m.blobsDiscoveryKey)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      blobsKey: r0,
      blobsDiscoveryKey: r1
    }
  }
}

// @punch-remote/objects
const encoding1 = {
  preencode (state, m) {
    c.string.preencode(state, m.oid)
    c.json.preencode(state, m.blobId)
    c.string.preencode(state, m.type)
    c.uint.preencode(state, m.size)
    c.string.preencode(state, m.refOid)
  },
  encode (state, m) {
    c.string.encode(state, m.oid)
    c.json.encode(state, m.blobId)
    c.string.encode(state, m.type)
    c.uint.encode(state, m.size)
    c.string.encode(state, m.refOid)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.json.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.string.decode(state)

    return {
      oid: r0,
      blobId: r1,
      type: r2,
      size: r3,
      refOid: r4
    }
  }
}

// @punch-remote/refs
const encoding2 = {
  preencode (state, m) {
    c.string.preencode(state, m.oid)
    c.string.preencode(state, m.name)
  },
  encode (state, m) {
    c.string.encode(state, m.oid)
    c.string.encode(state, m.name)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      oid: r0,
      name: r1
    }
  }
}

// @punch-remote/objects/hyperdb#0
const encoding3 = {
  preencode (state, m) {
    c.json.preencode(state, m.blobId)
    c.string.preencode(state, m.type)
    c.uint.preencode(state, m.size)
    c.string.preencode(state, m.refOid)
  },
  encode (state, m) {
    c.json.encode(state, m.blobId)
    c.string.encode(state, m.type)
    c.uint.encode(state, m.size)
    c.string.encode(state, m.refOid)
  },
  decode (state) {
    const r1 = c.json.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.string.decode(state)

    return {
      oid: null,
      blobId: r1,
      type: r2,
      size: r3,
      refOid: r4
    }
  }
}

// @punch-remote/refs/hyperdb#1
const encoding4 = {
  preencode (state, m) {
    c.string.preencode(state, m.name)
  },
  encode (state, m) {
    c.string.encode(state, m.name)
  },
  decode (state) {
    const r1 = c.string.decode(state)

    return {
      oid: null,
      name: r1
    }
  }
}

// @punch-remote/config/hyperdb#2
const encoding5 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.blobsDiscoveryKey)
  },
  encode (state, m) {
    c.buffer.encode(state, m.blobsDiscoveryKey)
  },
  decode (state) {
    const r1 = c.buffer.decode(state)

    return {
      blobsKey: null,
      blobsDiscoveryKey: r1
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@punch-remote/config': return encoding0
    case '@punch-remote/objects': return encoding1
    case '@punch-remote/refs': return encoding2
    case '@punch-remote/objects/hyperdb#0': return encoding3
    case '@punch-remote/refs/hyperdb#1': return encoding4
    case '@punch-remote/config/hyperdb#2': return encoding5
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
