// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @punch-remote/config
const encoding0 = {
  preencode (state, m) {
    c.buffer.preencode(state, m.blobsKey)
    c.buffer.preencode(state, m.blobsDiscoveryKey)
  },
  encode (state, m) {
    c.buffer.encode(state, m.blobsKey)
    c.buffer.encode(state, m.blobsDiscoveryKey)
  },
  decode (state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      blobsKey: r0,
      blobsDiscoveryKey: r1
    }
  }
}

// @punch-remote/refs.objectKeys
const encoding1_2 = c.array(c.json)

// @punch-remote/refs
const encoding1 = {
  preencode (state, m) {
    c.string.preencode(state, m.oid)
    c.string.preencode(state, m.name)
    state.end++ // max flag is 1 so always one byte

    if (m.objectKeys) encoding1_2.preencode(state, m.objectKeys)
  },
  encode (state, m) {
    const flags = m.objectKeys ? 1 : 0

    c.string.encode(state, m.oid)
    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (m.objectKeys) encoding1_2.encode(state, m.objectKeys)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      oid: r0,
      name: r1,
      objectKeys: (flags & 1) !== 0 ? encoding1_2.decode(state) : null
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@punch-remote/config': return encoding0
    case '@punch-remote/refs': return encoding1
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
